version: '2'
services:
 scraper-app:
   image: kudor/crypto-scraper
   build: crypto-scraper
   restart: always
   environment:
    - "SPRING_PROFILES_ACTIVE=production"
    - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/crypto_scraper_db"
    - "SPRING_DATASOURCE_USERNAME=root"
    - "SPRING_DATASOURCE_PASSWORD=secret"
 db:
  image: mysql:8
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: secret
   MYSQL_DATABASE: crypto_scraper_db
  ports:
   - "3306:3306"
  volumes:
   - db-data:/var/lib/mysql
 bi-app:
   build: bi
   restart: always
   environment:
    - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/crypto_scraper_db"
    - "SPRING_DATASOURCE_USERNAME=root"
    - "SPRING_DATASOURCE_PASSWORD=secret"
volumes:
 db-data:
